---
service_id: 1d7905ad-b3f7-49fb-b8a2-e0b697be8da7
definitions: "{{ [ lookup('file', './files/service-deployment.yaml') | from_yaml, lookup('file', './files/mariadb-data-persistentvolumeclaim.yaml') | from_yaml, lookup('file', './files/service-service.yaml') | from_yaml ] }}"